version: '2'
services:
  web: &web
    command: bundle exec bin/rails s -b 0.0.0.0 -p 3000
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    environment:
      DATABASE_URL: postgres://postgres:@db
      WEB_CONCURRENCY: 1
      RAILS_MAX_THREADS: 5
      LAUNCHY_DEBUG: 'true'
      REDIS_URL: redis://redis_db:6379
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis_db
  db:
    image: postgres:9.5
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  redis_db:
    image: redis:latest
    ports:
      - 6379:6379
volumes:
  bundle:
  db_data:
